# Generated by Django 4.2.6 on 2023-12-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF_Details',
            fields=[
                ('pdf_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_name', models.CharField(max_length=255)),
                ('pdf_vectordb_path', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdf_files/')),
            ],
        ),
    ]
